Repository UPbrella/UPbrella_front, pull requests merged in 2023-09, with the labels that each got.

#79 Merge: develop -> release-dev
  nginx/nginx.conf
  package-lock.json
  package.json
  src/App.tsx
  src/api/formApi.ts
  src/api/rentHistoryApi.ts
  src/components/atoms/Form/BankContent/index.stories.tsx
  src/components/atoms/Form/FormBasic/index.tsx
  src/components/atoms/Form/FormLocation/index.tsx
  src/components/atoms/Form/FormStatus/index.tsx
  src/components/atoms/Form/RentModalAccount/index.tsx
  src/components/atoms/SignUp/SignUpFormInputBankName/index.tsx
  src/components/molecules/FormLocationMolecules/index.tsx
  src/components/molecules/SignUp/SignUpInputAccountBox/index.tsx
  src/components/organisms/BankModal/index.tsx
  src/components/organisms/admin/StoreTable.tsx
  src/components/pages/SignUp/index.tsx
  src/components/pages/admin/RentHistoryPage.tsx
  src/components/pages/admin/rent/RentHistoryPage.tsx
  src/components/pages/rent/index.tsx
  src/components/pages/return/index.tsx
  src/components/templates/SignUp/SignUpNotRequired/index.tsx
  src/components/templates/SignUp/SignUpRequired/index.tsx
  src/components/templates/admin/AdminMenu.tsx
  src/hooks/queries/formQueries.ts
  src/hooks/queries/rentQueries.ts
  src/hooks/queries/storeQueries.ts
  src/routes/adminRouter.ts
  src/routes/notLayoutRouter.ts
  src/types/admin/RentTypes.ts
  src/types/form/FormTypes.ts
Labels: 📂 Chore

#80 Merge: release-dev -> release
  nginx/nginx.conf
  package-lock.json
  package.json
  src/App.tsx
  src/api/formApi.ts
  src/api/rentHistoryApi.ts
  src/components/atoms/Form/BankContent/index.stories.tsx
  src/components/atoms/Form/FormBasic/index.tsx
  src/components/atoms/Form/FormLocation/index.tsx
  src/components/atoms/Form/FormStatus/index.tsx
  src/components/atoms/Form/RentModalAccount/index.tsx
  src/components/atoms/SignUp/SignUpFormInputBankName/index.tsx
  src/components/molecules/FormLocationMolecules/index.stories.tsx
  src/components/molecules/FormLocationMolecules/index.tsx
  src/components/molecules/SignUp/SignUpInputAccountBox/index.tsx
  src/components/organisms/BankModal/index.tsx
  src/components/organisms/admin/StoreTable.tsx
  src/components/pages/SignUp/index.tsx
  src/components/pages/admin/RentHistoryPage.tsx
  src/components/pages/admin/rent/RentHistoryPage.tsx
  src/components/pages/rent/index.tsx
  src/components/pages/return/index.tsx
  src/components/templates/SignUp/SignUpNotRequired/index.tsx
  src/components/templates/SignUp/SignUpRequired/index.tsx
  src/components/templates/admin/AdminMenu.tsx
  src/hooks/queries/formQueries.ts
  src/hooks/queries/rentQueries.ts
  src/hooks/queries/storeQueries.ts
  src/routes/adminRouter.ts
  src/routes/notLayoutRouter.ts
  src/types/admin/RentTypes.ts
  src/types/form/FormTypes.ts
Labels: 📂 Chore

#81 Merge: release -> release-dev
  nginx/nginx.conf
Labels: 📂 Chore

#82 Merge: release-dev -> develop
  nginx/nginx.conf
  src/components/molecules/FormLocationMolecules/index.stories.tsx
Labels: 📂 Chore

#76 feat: 모바일 헤더 메뉴
  index.html
  src/components/atoms/LocationClassificationBtn/index.tsx
  src/components/molecules/Header/HeaderContents.tsx
  src/components/molecules/MobileMenu/index.stories.tsx
  src/components/molecules/MobileMenu/index.tsx
  src/components/organisms/Header/HeaderContainer.tsx
  src/components/pages/RentalLocation/RentalLocationPage.tsx
  src/components/pages/home/HomeMainPage.tsx
  src/components/pages/rentalOffice/RentalOfficePage.tsx
  src/components/templates/common/MainLayout.tsx
  src/types/commonTypes.ts
  tailwind.config.js
Labels: 🎨 Style

#77 feat: phoneNumber 포맷팅 유틸함수
  src/components/pages/admin/store/UI/StoreModal.tsx
  src/utils/utils.ts
Labels: 📌 Feature

#84 feat: 어드민 > 회원 조회 및 삭제 API 코드 추가
  src/api/userApi.ts
  src/hooks/queries/userQueries.ts
  src/types/admin/userTypes.ts
Labels: 📌 Feature

#85 style: 어드민 > 회원 관리 테이블 ui 작업
  src/components/organisms/admin/StoreTable.tsx
  src/components/pages/admin/components/Table.tsx
  src/components/pages/admin/rent/RentHistoryPage.tsx
  src/components/pages/admin/store/UI/ClassificationTagModal.tsx
  src/components/pages/admin/user/UserAdminPage.tsx
  src/components/pages/admin/user/helper.ts
  src/components/pages/home/HomeMainPage.tsx
  src/components/templates/admin/AdminMenu.tsx
  src/routes/adminRouter.ts
Labels: 🎨 Style, 💥 Refactor

#87 Feat, Refactor, Style: PR 관련 피드백 반영, 로그인 기능 구현
  package-lock.json
  package.json
  src/App.tsx
  src/components/atoms/Mypage/MypageRentSection/index.stories.tsx
  src/components/atoms/Mypage/MypageRentSection/index.tsx
  src/components/atoms/Mypage/ProfileRent/index.tsx
  src/components/atoms/SignUp/SignUpFormInputBankName/index.tsx
  src/components/pages/Login/LoginRedirectPage/index.tsx
  src/components/pages/SignUp/index.tsx
  src/recoil/index.ts
Labels: 🎨 Style, 📌 Feature, 💥 Refactor

#88 feat: 어드민 > 대여반납 조회 페이지네이션 기능 추가
  package-lock.json
  package.json
  src/App.tsx
  src/api/rentHistoryApi.ts
  src/components/pages/admin/rent/RentHistoryPage.tsx
  src/components/pages/admin/rent/helper.ts
  src/components/pages/admin/store/UI/StoreList.tsx
  src/components/pages/home/HomeMainPage.tsx
  src/components/templates/common/MainLayout.tsx
  src/hooks/custom/usePaginator.ts
  src/hooks/queries/rentQueries.ts
  src/types/admin/RentTypes.ts
Labels: 📌 Feature, 💥 Refactor

#89 fix: 어드민 API 경로 수정
  src/api/rentHistoryApi.ts
  src/api/storeApi.ts
  src/api/userApi.ts
Labels: 🛠️ Bug

#91 hotfix: 수정된 Login api 반영하여 코드 수정
  src/components/pages/Login/LoginRedirectPage/index.tsx
Labels: 🛠️ Bug

#90 feat: return form setting
  src/components/atoms/Form/BankContent/index.stories.tsx
  src/components/atoms/Form/BankContent/index.tsx
  src/components/atoms/Form/FormButton/index.tsx
  src/components/atoms/Form/FormStatus/index.tsx
  src/components/atoms/Form/RentModalAccount/index.tsx
  src/components/atoms/Form/ReturnModal/index.tsx
  src/components/molecules/FormLocationMolecules/index.stories.tsx
  src/components/molecules/FormLocationMolecules/index.tsx
  src/components/molecules/Header/HeaderContents.tsx
  src/components/pages/rent/index.tsx
  src/components/pages/return/index.tsx
Labels: 📌 Feature

#92 feat: 어드민 > 회원관리, 블랙리스트, 관리자 권한 변경 기능 추가
  src/api/rentHistoryApi.ts
  src/api/userApi.ts
  src/components/pages/admin/rent/RentHistoryPage.tsx
  src/components/pages/admin/user/UserAdminPage.tsx
  src/components/pages/admin/user/helper.ts
  src/hooks/queries/rentQueries.ts
  src/hooks/queries/userQueries.ts
  src/types/admin/userTypes.ts
  src/utils/utils.ts
Labels: 📌 Feature, 💥 Refactor

#93 feat: 대분류 태그 별 협업 지점 목록
  src/api/storeApi.ts
  src/assets/webMarker.svg
  src/assets/webMarker_inactive.svg
  src/components/atoms/BottomSheet/index.tsx
  src/components/atoms/LocationClassificationBtn/index.stories.tsx
  src/components/atoms/LocationClassificationBtn/index.tsx
  src/components/atoms/MobileCardInfo/index.stories.tsx
  src/components/atoms/MobileCardInfo/index.tsx
  src/components/atoms/NaverDirectionBtn/index.tsx
  src/components/molecules/Header/HeaderContents.tsx
  src/components/molecules/MobileCard/index.stories.tsx
  src/components/molecules/MobileCard/index.tsx
  src/components/pages/RentalLocation/RentalLocationPage.tsx
  src/hooks/queries/storeQueries.ts
  src/styles/markerLabel.css
  src/types/admin/StoreTypes.ts
Labels: 🎨 Style, 📌 Feature

#94 style: 협업지점 바텀시트
  src/App.tsx
Labels: 🎨 Style

#95 Feat: mypage CSS 보완, 왼쪽 nav 기능 완성, 로그인 상태관리 관련 에러해결
  src/components/atoms/Header/HeaderMyPage.tsx
  src/components/atoms/Mypage/MypageNavSection/index.stories.tsx
  src/components/atoms/Mypage/MypageNavSection/index.tsx
  src/components/atoms/Mypage/MypageRentSection/index.tsx
  src/components/atoms/Mypage/ProfileRent/index.tsx
  src/components/molecules/Mypage/MypageNav/index.stories.tsx
  src/components/molecules/Mypage/MypageNav/index.tsx
  src/components/molecules/Mypage/MypageRentList/index.tsx
  src/components/organisms/Header/HeaderContainer.tsx
  src/components/organisms/Mypage/MypageLeftCard/index.stories.tsx
  src/components/organisms/Mypage/MypageLeftCard/index.tsx
  src/components/organisms/Mypage/MypageRentCard/index.tsx
  src/components/pages/Mypage/MypageAccountPage/index.tsx
  src/components/pages/Mypage/MypageRentPage/index.tsx
  src/components/pages/home/HomeMainPage.tsx
  src/recoil/index.ts
  src/routes/layoutRouter.ts
  vite.config.ts
Labels: 🛠️ Bug, 🎨 Style, 📌 Feature

#98 feat: 우산 반납 신청
  src/api/formApi.ts
  src/components/atoms/Form/FormStatus/index.tsx
  src/components/atoms/Form/ReturnModal/index.tsx
  src/components/pages/return/index.tsx
  src/hooks/queries/formQueries.ts
  src/types/form/FormTypes.ts
Labels: 📌 Feature

#102 fix: 배포 전 버그 수정
  src/api/formApi.ts
  src/components/atoms/Form/FormStatus/index.tsx
  src/components/molecules/Header/HeaderContents.tsx
  src/components/molecules/Mypage/MypageNav/index.tsx
  src/components/pages/home/HomeMainPage.tsx
  src/components/pages/rent/index.tsx
  src/components/pages/rentalOffice/RentalOfficePage.tsx
  src/types/form/FormTypes.ts
Labels: 🛠️ Bug

#107 fix: 카카오 로그인 url 변경
  package.json
  src/components/pages/Login/LoginPage/index.tsx
Labels: 💥 Refactor

#111 feat: 폼 URL 연결, 예외 처리
  src/components/pages/home/HomeMainPage.tsx
  src/components/pages/rent/index.tsx
  src/components/pages/return/index.tsx
  src/hooks/queries/formQueries.ts
  src/routes/notLayoutRouter.ts
Labels: 📌 Feature

#115 Fix: 로그인 플로우 오류 수정
  package-lock.json
  package.json
  src/components/organisms/Header/HeaderContainer.tsx
  src/components/pages/Login/LoginRedirectPage/index.tsx
  src/components/pages/Mypage/MypageRentPage/index.tsx
  src/recoil/index.ts
Labels: 🛠️ Bug

#114 feat: 협업지점 소개 페이지 전체 리스트 조회 및 스크롤 이동
  src/api/storeApi.ts
  src/components/atoms/LocationClassificationBtn/index.tsx
  src/components/molecules/Store/index.stories.tsx
  src/components/molecules/Store/index.tsx
  src/components/organisms/Card/index.tsx
  src/components/organisms/ImgSwiper/index.stories.tsx
  src/components/organisms/ImgSwiper/index.tsx
  src/components/organisms/ImgSwiper/styles.css
  src/components/pages/rentalOffice/RentalOfficePage.tsx
  src/hooks/queries/storeQueries.ts
  src/types/admin/StoreTypes.ts
Labels: 🎨 Style, 📌 Feature, 💥 Refactor

#124 fix: 로그인, 로그아웃 흐름 수정
  src/App.tsx
  src/components/atoms/Header/HeaderMyPage.tsx
  src/components/molecules/Header/HeaderContents.tsx
  src/components/molecules/MobileMenu/index.stories.tsx
  src/components/molecules/MobileMenu/index.tsx
  src/components/organisms/Header/HeaderContainer.tsx
  src/components/pages/Login/LoginPage/index.tsx
  src/components/pages/Login/LoginRedirectPage/index.tsx
  src/hooks/queries/userQueries.ts
  src/types/commonTypes.ts
Labels: 🛠️ Bug, 📌 Feature, 💥 Refactor

#116 fix: 어드민 > 회원, 대여반납 조회 예외 처리
  src/components/pages/admin/rent/RentHistoryPage.tsx
  src/components/pages/admin/user/UserAdminPage.tsx
  src/components/pages/admin/user/helper.ts
  src/components/templates/admin/AdminMenu.tsx
  src/types/admin/userTypes.ts
Labels: 🛠️ Bug, 📌 Feature, 💥 Refactor

#119 feat: 어드민 > 우산관리 API, Type, Queries 추가
  src/api/umbrellaApi.ts
  src/components/pages/admin/feedback/UmbrellaFeedBackPage.tsx
  src/components/pages/admin/umbrella/UmbrellaAdminPage.tsx
  src/components/templates/admin/AdminMenu.tsx
  src/hooks/queries/umbrellaQueries.ts
  src/routes/adminRouter.ts
  src/types/admin/umbrellaTypes.ts
Labels: 📌 Feature

#121 style: 에러 컴포넌트
  src/assets/errorpage_img.png
  src/components/molecules/ErrorComponent/index.stories.tsx
  src/components/molecules/ErrorComponent/index.tsx
Labels: 🎨 Style

#113 feat: 이용 안내 정보성 페이지(우산 대여 안내)
  src/App.tsx
  src/assets/rental_step1.png
  src/assets/rental_step2.png
  src/assets/rental_step3.png
  src/assets/rental_step3_2.png
  src/assets/rental_step4.png
  src/assets/rental_step5.png
  src/assets/webMarker_inactive.png
  src/components/atoms/InformTitle/index.stories.tsx
  src/components/atoms/InformTitle/index.tsx
  src/components/atoms/MobileCardInfo/index.tsx
  src/components/molecules/MobileCard/indes.stories.tsx
  src/components/pages/Info/InfoPage.tsx
  src/routes/layoutRouter.ts
Labels: 🎨 Style

#133 fix: 폼 이슈정리, feat: 로그인 리다이렉트
  src/App.tsx
  src/components/molecules/ErrorComponent/index.tsx
  src/components/organisms/MobileHeader/index.stories.tsx
  src/components/organisms/MobileHeader/index.tsx
  src/components/pages/Login/LoginPage/index.tsx
  src/components/pages/Login/LoginRedirectPage/index.tsx
  src/components/pages/rent/index.tsx
  src/components/pages/return/index.tsx
  src/hooks/queries/userQueries.ts
  src/recoil/index.ts
  src/utils/PrivateRoutes.tsx
Labels: 🛠️ Bug, 📌 Feature, 💥 Refactor

#128 feat: 협업지점 상세 카드 api 연결
  src/api/storeApi.ts
  src/components/atoms/RentalLocationTitle/index.stories.tsx
  src/components/atoms/RentalLocationTitle/index.tsx
  src/components/organisms/Card/index.tsx
  src/components/organisms/ImgSwiper/index.tsx
  src/components/organisms/RentalInfoCard/index.tsx
  src/components/pages/rentalOffice/RentalOfficePage.tsx
Labels: 📌 Feature

#137 feat: 어드민 > 우산 관리 페이지 개발 완료
  package-lock.json
  package.json
  src/api/umbrellaApi.ts
  src/components/molecules/SelectBox/index.tsx
  src/components/organisms/admin/StoreTable.tsx
  src/components/pages/admin/store/UI/StoreImagesModal.tsx
  src/components/pages/admin/store/helper.ts
  src/components/pages/admin/umbrella/UI/UmbrellaModal.tsx
  src/components/pages/admin/umbrella/UmbrellaAdminPage.tsx
  src/components/pages/admin/umbrella/helper.ts
  src/components/pages/admin/umbrella/types.ts
  src/hooks/queries/umbrellaQueries.ts
  src/types/admin/StoreTypes.ts
  src/types/admin/umbrellaTypes.ts
  src/types/null.d.ts
  src/utils/error.ts
Labels: 📌 Feature

#132 feat: 모바일 반응형 카드
  src/components/atoms/BottomSheet/index.tsx
  src/components/atoms/RentalLocationTitle/index.tsx
  src/components/molecules/Store/index.tsx
  src/components/organisms/Card/index.tsx
  src/components/organisms/ImgSwiper/index.tsx
  src/components/organisms/RentalInfoCard/index.tsx
  src/components/pages/rentalOffice/RentalOfficePage.tsx
  src/routes/layoutRouter.ts
Labels: 🎨 Style, 📌 Feature

#134 feat: 사용자 위치에서 협업 지점까지 네이버 길찾기
  src/components/atoms/NaverDirectionBtn/index.stories.tsx
  src/components/atoms/NaverDirectionBtn/index.tsx
  src/components/molecules/MobileCard/index.tsx
  src/components/organisms/RentalInfoCard/index.tsx
  src/components/pages/RentalLocation/RentalLocationPage.tsx
Labels: 📌 Feature

#122 feat: 계좌 등록, 삭제, 변경 기능
  src/components/atoms/Mypage/MypageBankInput/index.stories.tsx
  src/components/atoms/Mypage/MypageBankInput/index.tsx
  src/components/atoms/Mypage/MypageFormTitle/index.stories.tsx
  src/components/atoms/Mypage/MypageFormTitle/index.tsx
  src/components/molecules/Mypage/MypageBankAccountInput/index.stories.tsx
  src/components/molecules/Mypage/MypageBankAccountInput/index.tsx
  src/components/organisms/Mypage/MypageAccountCard/index.stories.tsx
  src/components/organisms/Mypage/MypageAccountCard/index.tsx
  src/components/organisms/Mypage/MypageLeftCard/index.stories.tsx
  src/components/organisms/Mypage/MypageLeftCard/index.tsx
  src/components/pages/Mypage/MypageAccountPage/index.tsx
  src/components/pages/Mypage/MypageRentPage/index.tsx
Labels: 📌 Feature

#127 FEAT: 개인정보 조회 페이지 기능구현
  src/components/atoms/Mypage/MypageFormContent/index.tsx
  src/components/atoms/Mypage/MypageFormTitle/index.tsx
  src/components/molecules/Mypage/MypageBankAccountInput/index.tsx
  src/components/molecules/Mypage/MypageInfoSection/index.stories.tsx
  src/components/molecules/Mypage/MypageInfoSection/index.tsx
  src/components/organisms/Mypage/MypageInfoCard/index.stories.tsx
  src/components/organisms/Mypage/MypageInfoCard/index.tsx
  src/components/pages/Mypage/MypageInfoPage/index.tsx
  src/components/pages/SignUp/index.tsx
  src/routes/layoutRouter.ts
Labels: 📌 Feature

#138 feat: 어드민 > 상태신고 / 개선사항 확인 페이지 추가
  src/api/feedBackApi.ts
  src/components/atoms/FeedBackDataTable/index.tsx
  src/components/pages/admin/feedback/UmbrellaFeedBackPage.tsx
  src/hooks/queries/feedBackQueries.ts
  src/types/admin/FeedBackTypes.ts
Labels: 🎨 Style, 📌 Feature

#142 feat: 유저 어드민 구분 리다이렉트, 어드민관련 메뉴 분리
  src/App.tsx
  src/components/molecules/Header/HeaderContents.tsx
  src/components/molecules/MobileMenu/index.stories.tsx
  src/components/molecules/MobileMenu/index.tsx
  src/components/organisms/Header/HeaderContainer.tsx
  src/components/pages/forbidden/ForbiddenPage.tsx
  src/components/pages/return/index.tsx
  src/components/pages/temp/TempPage.tsx
  src/hooks/queries/userQueries.ts
  src/routes/layoutRouter.ts
  src/routes/notLayoutRouter.ts
  src/types/admin/userTypes.ts
  src/utils/AdminRoutes.tsx
Labels: 📌 Feature, 💥 Refactor

#145 feat: 업브렐라 카카오톡 플러스친구 연결
  src/components/molecules/Footer/FooterSNS/index.tsx
Labels: 📌 Feature

#147 Feat: 회원가입 페이지 유효성검사
  src/components/atoms/SignUp/SignUpFormAllAllowText/index.tsx
  src/components/atoms/SignUp/SignUpFormAllowChevron/index.tsx
  src/components/atoms/SignUp/SignUpFormAllowText/index.tsx
  src/components/molecules/SignUp/SignUpAllAllowBox/index.tsx
  src/components/molecules/SignUp/SignUpAllowBox/index.tsx
  src/components/molecules/SignUp/SignUpInputBox/index.tsx
  src/components/pages/SignUp/index.tsx
  src/components/pages/pp/index.tsx
  src/components/pages/tos/index.tsx
  src/components/templates/SignUp/SignUpRequired/index.tsx
  src/routes/layoutRouter.ts
Labels: 📌 Feature

#143 fix: 어드민 > 협업지점 활성화여부 기능 수정
  src/App.tsx
  src/api/storeApi.ts
  src/components/organisms/admin/StoreTable.tsx
  src/components/pages/RentalLocation/RentalLocationPage.tsx
  src/components/pages/admin/store/UI/StoreAddressInput.tsx
  src/components/pages/admin/store/UI/StoreList.tsx
  src/components/pages/admin/store/UI/StoreModalBody.tsx
  src/components/pages/admin/store/helper.ts
  src/hooks/queries/storeQueries.ts
  src/types/admin/StoreTypes.ts
  src/types/commonTypes.ts
  src/utils/admin/storeHelpers.tsx
Labels: 🛠️ Bug, 🎨 Style, 💥 Refactor

#144 feat: 랜딩 페이지 작업 (업브렐라 이야기)
  src/App.tsx
  src/assets/Story/main_section1_bg.png
  src/assets/Story/section3.png
  src/assets/Story/section4-1.jpeg
  src/assets/Story/section4-2.jpeg
  src/assets/Story/section4-3.jpeg
  src/assets/Story/section4-4.jpeg
  src/assets/Story/section5_bg.png
  src/assets/Story/section8_bg.png
  src/components/molecules/Header/HeaderContents.tsx
  src/components/molecules/MobileCard/indes.stories.tsx
  src/components/organisms/Footer/index.tsx
  src/components/pages/story/UI/SectionBullet.tsx
  src/components/pages/story/UI/StorySection1.tsx
  src/components/pages/story/UI/StorySection2.tsx
  src/components/pages/story/UI/StorySection3.tsx
  src/components/pages/story/UI/StorySection4.tsx
  src/components/pages/story/UI/StorySection5.tsx
  src/components/pages/story/UI/StorySection6.tsx
  src/components/pages/story/UI/StorySection7.tsx
  src/components/pages/story/UI/StorySection8.tsx
  src/components/pages/story/UpbrellaStoryPage.tsx
  src/components/pages/story/data.ts
  src/components/templates/common/MainLayout.tsx
  src/routes/layoutRouter.ts
  src/utils/PrivateRoutes.tsx
  tailwind.config.js
Labels: 🎨 Style, 📌 Feature

#157 refactor: 폼 에러컴포넌트 메시지 백엔드에서 받아옴
  src/components/atoms/Form/RentModalAccount/index.tsx
  src/components/pages/rent/index.tsx
  src/components/pages/return/index.tsx
Labels: 💥 Refactor

#154 fix: left rent card 오류 수정
  src/components/organisms/Mypage/MypageLeftCard/index.tsx
Labels: 🛠️ Bug

#164 hotfix: background-image 버그 수정
  public/assets/main_section1_bg.png
  public/assets/section5_bg.png
  public/assets/section8_bg.png
  src/components/pages/story/UI/StorySection1.tsx
  src/components/pages/story/UI/StorySection5.tsx
  src/components/pages/story/UI/StorySection8.tsx
  tailwind.config.js
Labels: 🛠️ Bug

#162 feat: 모바일 반응형 카드 스타일 변경
  src/components/atoms/LocationClassificationBtn/index.tsx
  src/components/molecules/Store/index.tsx
  src/components/pages/RentalLocation/RentalLocationPage.tsx
  src/components/pages/RentalLocation/webMarker.svg
  src/components/pages/rentalOffice/RentalOfficePage.tsx
  tailwind.config.js
Labels: 🎨 Style

#161 feat: 신고내역, 개선사항 최대글자수 지정
  src/components/atoms/Form/FormLocation/index.tsx
  src/components/atoms/Form/FormStatus/index.tsx
  src/components/pages/rent/index.tsx
  src/components/pages/return/index.tsx
Labels: 🎨 Style, 📌 Feature

#170 feat: mypage 모달 디자인, 개발
  src/components/molecules/Footer/FooterLabel/index.tsx
  src/components/molecules/Mypage/MypageModal/index.tsx
  src/components/molecules/Mypage/MypageModalChildren/index.tsx
  src/components/molecules/Mypage/MypageModalNotAllowedChildren/index.tsx
  src/components/molecules/Mypage/MypageModalTwoBtnChildren/index.tsx
  src/components/pages/Mypage/MypageAccountPage/index.tsx
  src/components/pages/Mypage/MypageInfoPage/index.tsx
  src/components/pages/Mypage/MypageRentPage/index.tsx
Labels: 🎨 Style, 📌 Feature

#168 style: 이용안내 페이지 반응형
  src/App.tsx
  src/components/atoms/InformTitle/index.tsx
  src/components/molecules/Footer/FooterSNS/index.tsx
  src/components/organisms/Footer/index.tsx
  src/components/organisms/Info/FAQ/index.tsx
  src/components/organisms/Info/HowRent/index.tsx
  src/components/organisms/Info/HowReturn/index.tsx
  src/components/pages/Info/InfoPage.tsx
  src/components/pages/RentalLocation/RentalLocationPage.tsx
  src/components/pages/story/UI/StorySection3.tsx
  src/components/pages/story/UI/StorySection4.tsx
  tailwind.config.js
Labels: 🎨 Style
