Repository UPbrella/UPbrella_front, pull requests merged in 2023-11, with the labels that each got.

#240 fix: build에러 수정
  src/components/molecules/Mypage/MypageRentList/index.stories.tsx
  src/components/organisms/Mypage/MypageRentCard/index.tsx
  src/hooks/queries/userQueries.ts
Labels: 🛠️ Bug

#241 Deploy: release-dev배포입니다.
  src/components/molecules/Mypage/MypageRentList/index.stories.tsx
  src/components/organisms/Mypage/MypageRentCard/index.tsx
  src/hooks/queries/userQueries.ts
Labels: 💾 Deploy

#239 Release dev
  src/components/atoms/Login/LoginTitle/index.tsx
  src/components/molecules/Mypage/MypageRentList/index.stories.tsx
  src/components/molecules/Mypage/MypageRentList/index.tsx
  src/components/organisms/Mypage/MypageRentCard/index.tsx
  src/components/pages/Mypage/MypageAccountPage/index.tsx
  src/components/pages/Mypage/MypageInfoPage/index.tsx
  src/components/pages/Mypage/MypageRentPage/index.tsx
  src/components/pages/SignUp/index.tsx
  src/components/templates/SignUp/SignUpNotRequired/index.tsx
  src/components/templates/SignUp/SignUpRequired/index.tsx
  src/hooks/queries/userQueries.ts
  src/types/mypage/MypageTypes.ts
  src/types/signup/SignupTypes.ts
Labels: 💾 Deploy

#242 design: lg사이즈에서 폰트크기, 마진 크기 수정
  src/components/molecules/Mypage/MypageModal/index.tsx
  src/components/molecules/Mypage/MypageModalChildren/index.tsx
  src/components/molecules/Mypage/MypageModalTwoBtnChildren/index.tsx
Labels: 🎨 Style

#243 Deploy: Release-dev 배포입니다.
  src/components/molecules/Mypage/MypageModal/index.tsx
  src/components/molecules/Mypage/MypageModalChildren/index.tsx
  src/components/molecules/Mypage/MypageModalTwoBtnChildren/index.tsx
Labels: 💾 Deploy

#246 fix: QA 대응 (업브렐라이야기, 우산어드민)
  src/components/pages/admin/umbrella/UI/UmbrellaModal.tsx
  src/components/pages/story/UI/StorySection2.tsx
  src/components/pages/story/UI/StorySection8.tsx
  src/components/pages/story/UpbrellaStoryPage.tsx
Labels: 🛠️ Bug, 🎨 Style

#249 fix: 헤더 고정 및 footer 수정
  src/components/organisms/Footer/index.tsx
  src/components/organisms/Header/HeaderContainer.tsx
  src/components/pages/Info/InfoPage.tsx
  src/components/pages/Mypage/MypageAccountPage/index.tsx
  src/components/pages/Mypage/MypageContactPage/index.tsx
  src/components/pages/Mypage/MypageInfoPage/index.tsx
  src/components/pages/Mypage/MypageRentPage/index.tsx
  src/components/pages/RentalLocation/RentalLocationPage.tsx
  src/components/pages/contact/ContactPage.tsx
  src/components/pages/rent/index.tsx
  src/components/pages/return/index.tsx
  src/components/pages/story/UpbrellaStoryPage.tsx
  src/components/pages/tos/index.tsx
  src/components/templates/Login/index.tsx
  src/components/templates/SignUp/SignUpNotRequired/index.tsx
  src/components/templates/SignUp/SignUpRequired/index.tsx
  src/components/templates/common/BackgroundLayout.tsx
  src/components/templates/common/MainLayout.tsx
  src/utils/AdminRoutes.tsx
  src/utils/PrivateRoutes.tsx
Labels: 🛠️ Bug, 🎨 Style, 💥 Refactor

#244 Deploy: Release 배포입니다.
  src/components/molecules/Mypage/MypageModal/index.tsx
  src/components/molecules/Mypage/MypageModalChildren/index.tsx
  src/components/molecules/Mypage/MypageModalTwoBtnChildren/index.tsx
Labels: 💾 Deploy

#251 fix: 화면 구역 별 스크롤 및 랜덤 스토어 지정
  src/components/molecules/Store/index.tsx
  src/components/pages/rentalOffice/RentalOfficePage.tsx
Labels: 🛠️ Bug, 🎨 Style, 📌 Feature

#253 Deploy: Release
  src/components/molecules/Store/index.tsx
  src/components/organisms/Footer/index.tsx
  src/components/organisms/Header/HeaderContainer.tsx
  src/components/pages/Info/InfoPage.tsx
  src/components/pages/Mypage/MypageAccountPage/index.tsx
  src/components/pages/Mypage/MypageContactPage/index.tsx
  src/components/pages/Mypage/MypageInfoPage/index.tsx
  src/components/pages/Mypage/MypageRentPage/index.tsx
  src/components/pages/RentalLocation/RentalLocationPage.tsx
  src/components/pages/admin/umbrella/UI/UmbrellaModal.tsx
  src/components/pages/contact/ContactPage.tsx
  src/components/pages/rent/index.tsx
  src/components/pages/rentalOffice/RentalOfficePage.tsx
  src/components/pages/return/index.tsx
  src/components/pages/story/UI/StorySection2.tsx
  src/components/pages/story/UI/StorySection8.tsx
  src/components/pages/story/UpbrellaStoryPage.tsx
  src/components/pages/tos/index.tsx
  src/components/templates/Login/index.tsx
  src/components/templates/SignUp/SignUpNotRequired/index.tsx
  src/components/templates/SignUp/SignUpRequired/index.tsx
  src/components/templates/common/BackgroundLayout.tsx
  src/components/templates/common/MainLayout.tsx
  src/utils/AdminRoutes.tsx
  src/utils/PrivateRoutes.tsx
Labels: 💾 Deploy

#254 refactor: signup login 수정
  src/hooks/queries/userQueries.ts
Labels: 💥 Refactor
