Repository UPbrella/UPbrella_front, pull requests merged in 2023-10, with the labels that each got.

#169 feat: menuFooter 추가
  src/components/molecules/Footer/FooterLabel/index.tsx
  src/components/molecules/Header/HeaderContents.tsx
  src/components/molecules/MobileMenu/index.tsx
  src/components/organisms/CardFooter/index.tsx
Labels: 🎨 Style, 📌 Feature

#174 fix: 랜딩페이지 url -> 업브렐라 이야기 라우트로 변경
  src/App.tsx
  src/routes/notLayoutRouter.ts
Labels: 🛠️ Bug

#171 feat: 문의하기 페이지 개발
  src/components/molecules/Mypage/MypageContactSection/index.tsx
  src/components/organisms/Mypage/MypageContactCard/index.tsx
  src/components/pages/Mypage/MypageContactPage/index.tsx
  src/routes/layoutRouter.ts
Labels: 📌 Feature

#176 fix: 여러 버그 수정
  src/assets/rental_step1.png
  src/assets/rental_step2.png
  src/assets/rental_step3.png
  src/assets/rental_step3_2.png
  src/assets/rental_step4.png
  src/assets/rental_step5.png
  src/components/molecules/MapBtn/index.tsx
  src/components/organisms/RentalInfoCard/index.tsx
  src/components/pages/RentalLocation/RentalLocationPage.tsx
  src/styles/markerLabel.css
Labels: 🛠️ Bug, 🎨 Style

#178 fix: background 이미지 있는 router 분리, Footer 스타일 수정
  src/App.tsx
  src/components/organisms/Footer/index.tsx
  src/components/pages/contact/ContactPage.tsx
  src/components/templates/common/BackgroundLayout.tsx
  src/routes/backgroundImageRouter.ts
  src/routes/layoutRouter.ts
Labels: 🎨 Style

#181 style: 어드민 페이지 반응형 일부 적용
  src/components/pages/admin/feedback/UmbrellaFeedBackPage.tsx
  src/components/pages/admin/rent/RentHistoryPage.tsx
  src/components/pages/admin/store/StoreManagePage.tsx
  src/components/pages/admin/store/UI/StoreFormWrapper.tsx
  src/components/pages/admin/store/UI/StoreModal.tsx
  src/components/pages/admin/store/UI/StoreModalBody.tsx
  src/components/pages/admin/store/helper.ts
  src/components/pages/admin/umbrella/UmbrellaAdminPage.tsx
  src/components/pages/admin/user/UserAdminPage.tsx
  src/components/templates/admin/AdminMenu.tsx
  src/utils/admin/storeHelpers.tsx
Labels: 🎨 Style

#183 style: 업브렐라 이야기 > 반응형 화면 수정
  src/components/pages/story/UI/StorySection2.tsx
  src/components/pages/story/UI/StorySection3.tsx
  src/components/pages/story/UI/StorySection4.tsx
  src/components/pages/story/UI/StorySection6.tsx
Labels: 🎨 Style

#186 feat: 협업지점 상세카드 페이지 분리
  src/components/molecules/Header/HeaderContents.tsx
  src/components/molecules/Store/index.tsx
  src/components/organisms/Card/index.tsx
  src/components/organisms/CardFooter/index.tsx
  src/components/organisms/Footer/index.tsx
  src/components/organisms/ImgSwiper/index.tsx
  src/components/organisms/RentalInfoCard/index.tsx
  src/components/pages/officeDetail/OfficeDetailPage.tsx
  src/components/pages/rentalOffice/RentalOfficePage.tsx
  src/routes/layoutRouter.ts
  src/stories/assets/colors.svg
  tailwind.config.js
Labels: 🎨 Style, 📌 Feature

#173 fix: 회원가입 페이지 반응형 디자인, (마이페이지, 이용약관, 개인정보)페이지 footer추가, 배경이 필요한 페이지 따로 routing
  src/App.tsx
  src/components/atoms/SignUp/SignUpFormSubtitle/index.tsx
  src/components/pages/Mypage/MypageAccountPage/index.tsx
  src/components/pages/Mypage/MypageContactPage/index.tsx
  src/components/pages/Mypage/MypageInfoPage/index.tsx
  src/components/pages/Mypage/MypageRentPage/index.tsx
  src/components/pages/SignUp/index.tsx
  src/components/pages/contact/ContactPage.tsx
  src/components/pages/pp/index.tsx
  src/components/pages/tos/index.tsx
  src/components/templates/Login/index.tsx
  src/components/templates/SignUp/SignUpNotRequired/index.tsx
  src/components/templates/SignUp/SignUpRequired/index.tsx
  src/routes/backgroundRouter.ts
  src/routes/layoutRouter.ts
Labels: 🎨 Style

#187 fix: PR 충돌해결 하며 변경사항 수정
  src/App.tsx
  src/components/pages/Mypage/MypageContactPage/index.tsx
  src/components/pages/contact/ContactPage.tsx
  src/components/templates/Login/index.tsx
  src/components/templates/SignUp/SignUpNotRequired/index.tsx
  src/components/templates/SignUp/SignUpRequired/index.tsx
  src/routes/layoutRouter.ts
Labels: 🛠️ Bug

#190 feat: 바텀시트 지점 상세카드에 버튼 추가
  src/components/atoms/DetailBtn/index.stories.tsx
  src/components/atoms/DetailBtn/index.tsx
  src/components/atoms/NaverDirectionBtn/index.stories.tsx
  src/components/molecules/MobileCard/index.tsx
  src/components/pages/RentalLocation/RentalLocationPage.tsx
Labels: 🎨 Style, 📌 Feature

#196 refactor: header 리팩토링
  src/components/atoms/Header/HeaderLogo.tsx
  src/components/atoms/Login/LoginTitle/index.tsx
  src/components/molecules/Header/HeaderContents.tsx
  src/components/molecules/MobileMenu/index.tsx
  src/components/organisms/Footer/index.tsx
  src/components/organisms/Header/HeaderContainer.tsx
Labels: 🎨 Style, 💥 Refactor

#197 fix: 어드민 > 협업지점 API 변경 반영
  src/api/storeApi.ts
  src/components/pages/admin/store/UI/StoreImagesModal.tsx
  src/components/pages/admin/store/UI/StoreList.tsx
  src/components/pages/admin/store/UI/StoreModal.tsx
  src/components/pages/admin/store/UI/StoreModalBody.tsx
  src/components/pages/admin/store/helper.ts
  src/hooks/queries/storeQueries.ts
  src/types/admin/StoreTypes.ts
Labels: Code Style

#198 Deploy: release-dev
  src/api/storeApi.ts
  src/components/atoms/Header/HeaderLogo.tsx
  src/components/atoms/Login/LoginTitle/index.tsx
  src/components/molecules/Header/HeaderContents.tsx
  src/components/molecules/MobileMenu/index.tsx
  src/components/organisms/Footer/index.tsx
  src/components/organisms/Header/HeaderContainer.tsx
  src/components/pages/admin/store/UI/StoreImagesModal.tsx
  src/components/pages/admin/store/UI/StoreList.tsx
  src/components/pages/admin/store/UI/StoreModal.tsx
  src/components/pages/admin/store/UI/StoreModalBody.tsx
  src/components/pages/admin/store/helper.ts
  src/hooks/queries/storeQueries.ts
  src/types/admin/StoreTypes.ts
Labels: 💾 Deploy

#199 Deploy: Release
  src/api/storeApi.ts
  src/components/atoms/Header/HeaderLogo.tsx
  src/components/atoms/Login/LoginTitle/index.tsx
  src/components/molecules/Header/HeaderContents.tsx
  src/components/molecules/MobileMenu/index.tsx
  src/components/organisms/Footer/index.tsx
  src/components/organisms/Header/HeaderContainer.tsx
  src/components/pages/admin/store/UI/StoreImagesModal.tsx
  src/components/pages/admin/store/UI/StoreList.tsx
  src/components/pages/admin/store/UI/StoreModal.tsx
  src/components/pages/admin/store/UI/StoreModalBody.tsx
  src/components/pages/admin/store/helper.ts
  src/hooks/queries/storeQueries.ts
  src/types/admin/StoreTypes.ts
Labels: 💾 Deploy

#200 fix: 대여,반납 히스토리 엑셀 다운로드 버그 수정
  src/components/pages/admin/rent/RentHistoryPage.tsx
Labels: 🛠️ Bug

#201 hotfix: 대여소 위치 help 버튼 수정
  src/components/molecules/MapBtn/index.tsx
  src/components/pages/RentalLocation/RentalLocationPage.tsx
Labels: 🛠️ Bug, ✍️ Code Style

#203 feat: 지점 QR 코드 추가
  src/components/organisms/admin/StoreTable.tsx
  src/components/pages/admin/store/UI/StoreModal.tsx
  src/components/pages/admin/umbrella/UI/UmbrellaModal.tsx
Labels: 📌 Feature

#204 fix: build 에러 수정
  src/components/organisms/ImgSwiper/index.stories.tsx
Labels: 📂 Chore

#205 Deploy: Release-dev
  src/components/atoms/LocationClassificationBtn/index.tsx
  src/components/molecules/Footer/FooterSNS/index.tsx
  src/components/molecules/MapBtn/index.tsx
  src/components/molecules/Store/index.tsx
  src/components/organisms/Card/index.tsx
  src/components/organisms/CardFooter/index.tsx
  src/components/organisms/Header/HeaderContainer.tsx
  src/components/organisms/ImgSwiper/index.stories.tsx
  src/components/organisms/ImgSwiper/index.tsx
  src/components/organisms/Info/FAQ/index.tsx
  src/components/organisms/Info/HowRent/index.tsx
  src/components/organisms/Info/HowReturn/index.tsx
  src/components/organisms/RentalInfoCard/index.tsx
  src/components/organisms/admin/StoreTable.tsx
  src/components/pages/Info/InfoPage.tsx
  src/components/pages/RentalLocation/ClassificationsButtons.tsx
  src/components/pages/RentalLocation/RentalLocationPage.tsx
  src/components/pages/admin/rent/RentHistoryPage.tsx
  src/components/pages/admin/store/UI/StoreModal.tsx
  src/components/pages/admin/umbrella/UI/UmbrellaModal.tsx
  src/components/pages/officeDetail/OfficeDetailPage.tsx
  src/components/pages/rentalOffice/RentalOfficePage.tsx
  src/components/templates/common/BackgroundLayout.tsx
  src/components/templates/common/MainLayout.tsx
  src/styles/markerLabel.css
  tailwind.config.js
Labels: 📂 Chore

#206 Deploy: Release
  src/components/atoms/LocationClassificationBtn/index.tsx
  src/components/molecules/Footer/FooterSNS/index.tsx
  src/components/molecules/MapBtn/index.tsx
  src/components/molecules/Store/index.tsx
  src/components/organisms/Card/index.tsx
  src/components/organisms/CardFooter/index.tsx
  src/components/organisms/Header/HeaderContainer.tsx
  src/components/organisms/ImgSwiper/index.stories.tsx
  src/components/organisms/ImgSwiper/index.tsx
  src/components/organisms/Info/FAQ/index.tsx
  src/components/organisms/Info/HowRent/index.tsx
  src/components/organisms/Info/HowReturn/index.tsx
  src/components/organisms/RentalInfoCard/index.tsx
  src/components/organisms/admin/StoreTable.tsx
  src/components/pages/Info/InfoPage.tsx
  src/components/pages/RentalLocation/ClassificationsButtons.tsx
  src/components/pages/RentalLocation/RentalLocationPage.tsx
  src/components/pages/admin/rent/RentHistoryPage.tsx
  src/components/pages/admin/store/UI/StoreModal.tsx
  src/components/pages/admin/umbrella/UI/UmbrellaModal.tsx
  src/components/pages/officeDetail/OfficeDetailPage.tsx
  src/components/pages/rentalOffice/RentalOfficePage.tsx
  src/components/templates/common/BackgroundLayout.tsx
  src/components/templates/common/MainLayout.tsx
  src/styles/markerLabel.css
  tailwind.config.js
Labels: 📂 Chore

#210 fix: alert message 를 toast message로 변경
  src/components/pages/SignUp/index.tsx
Labels: 🛠️ Bug

#209 fix: 대여소 위치 페이지 ux 개선
  src/components/molecules/MapBtn/index.tsx
  src/components/pages/RentalLocation/RentalLocationPage.tsx
  src/utils/locationUtils.ts
  src/utils/map/mapHelper.ts
Labels: 💥 Refactor, ✍️ Code Style

#213 Deploy: Release Dev
  src/components/molecules/MapBtn/index.tsx
  src/components/pages/RentalLocation/RentalLocationPage.tsx
  src/components/pages/SignUp/index.tsx
  src/utils/locationUtils.ts
  src/utils/map/mapHelper.ts
Labels: 💾 Deploy

#214 Deploy: Release
  src/components/molecules/MapBtn/index.tsx
  src/components/pages/RentalLocation/RentalLocationPage.tsx
  src/components/pages/SignUp/index.tsx
  src/utils/locationUtils.ts
  src/utils/map/mapHelper.ts
Labels: 💾 Deploy

#208 fix: contactUs footer
  src/App.tsx
  src/components/organisms/Footer/index.tsx
  src/components/pages/contact/ContactPage.tsx
  src/routes/backgroundImageRouter.ts
  tailwind.config.js
Labels: 🛠️ Bug

#215 feat: 모바일의 경우 네이버지도 앱 연동
  src/components/atoms/NaverDirectionBtn/index.tsx
  src/components/molecules/MobileCard/index.tsx
Labels: 🛠️ Bug, 📌 Feature

#221 refactor: 네이버 길찾기 리팩토링
  package-lock.json
  package.json
  src/components/atoms/NaverDirectionBtn/index.stories.tsx
  src/components/atoms/NaverDirectionBtn/index.tsx
  src/components/molecules/MobileCard/index.tsx
  src/components/organisms/RentalInfoCard/index.tsx
Labels: 💥 Refactor

#222 Deploy: Release Dev
  package-lock.json
  package.json
  src/components/atoms/NaverDirectionBtn/index.stories.tsx
  src/components/atoms/NaverDirectionBtn/index.tsx
  src/components/molecules/MobileCard/index.tsx
  src/components/organisms/RentalInfoCard/index.tsx
  src/components/pages/RentalLocation/RentalLocationPage.tsx
Labels: 💾 Deploy

#223 Deploy: Release
  package-lock.json
  package.json
  src/App.tsx
  src/components/atoms/NaverDirectionBtn/index.stories.tsx
  src/components/atoms/NaverDirectionBtn/index.tsx
  src/components/molecules/MobileCard/index.tsx
  src/components/organisms/Footer/index.tsx
  src/components/pages/RentalLocation/RentalLocationPage.tsx
  src/components/pages/contact/ContactPage.tsx
  src/routes/backgroundImageRouter.ts
  tailwind.config.js
Labels: 💾 Deploy

#225 Deploy: Release Dev
  src/components/atoms/SignUp/SignUpFormAllowChevron/index.tsx
  src/components/pages/Mypage/MypageAccountPage/index.tsx
  src/components/pages/SignUp/index.tsx
  src/components/pages/admin/store/UI/StoreImagesModal.tsx
  src/utils/utils.ts
Labels: 💾 Deploy

#226 Deploy: Release
  src/components/atoms/SignUp/SignUpFormAllowChevron/index.tsx
  src/components/pages/Mypage/MypageAccountPage/index.tsx
  src/components/pages/SignUp/index.tsx
  src/components/pages/admin/store/UI/StoreImagesModal.tsx
  src/utils/utils.ts
Labels: 💾 Deploy

#227 refactor: 라우터 리팩토링
  src/App.tsx
  src/api/storeApi.ts
  src/components/atoms/DetailBtn/index.tsx
  src/components/atoms/Header/HeaderMyPage.tsx
  src/components/molecules/ErrorComponent/index.tsx
  src/components/molecules/Footer/FooterLabel/index.tsx
  src/components/molecules/MapBtn/index.tsx
  src/components/molecules/MobileMenu/index.tsx
  src/components/molecules/Mypage/MypageNav/index.tsx
  src/components/molecules/Store/index.tsx
  src/components/organisms/Header/HeaderContainer.tsx
  src/components/organisms/Info/HowReturn/index.tsx
  src/components/pages/Mypage/MypageAccountPage/index.tsx
  src/components/pages/Mypage/MypageContactPage/index.tsx
  src/components/pages/Mypage/MypageInfoPage/index.tsx
  src/components/pages/Mypage/MypageRentPage/index.tsx
  src/components/pages/SignUp/index.tsx
  src/components/pages/admin/store/UI/StoreModal.tsx
  src/components/pages/admin/store/UI/StoreModalBody.tsx
  src/components/pages/home/HomeMainPage.tsx
  src/components/pages/not-found/NotFound.tsx
  src/components/pages/story/UI/StorySection8.tsx
  src/components/templates/admin/AdminMenu.tsx
  src/components/templates/common/BackgroundLayout.tsx
  src/constants/Store.ts
  src/hooks/queries/userQueries.ts
  src/mocks/StoreDetail.tsx
  src/routes/adminRouter.ts
  src/routes/backgroundImageRouter.ts
  src/routes/backgroundRouter.ts
  src/routes/basicRouter.ts
  src/routes/layoutRouter.ts
  src/routes/notLayoutRouter.ts
  src/types/commonTypes.ts
  src/utils/AdminRoutes.tsx
Labels: 💥 Refactor

#228 Deploy: dev
  src/App.tsx
  src/api/storeApi.ts
  src/components/atoms/DetailBtn/index.tsx
  src/components/atoms/Header/HeaderMyPage.tsx
  src/components/molecules/ErrorComponent/index.tsx
  src/components/molecules/Footer/FooterLabel/index.tsx
  src/components/molecules/MapBtn/index.tsx
  src/components/molecules/MobileMenu/index.tsx
  src/components/molecules/Mypage/MypageNav/index.tsx
  src/components/molecules/Store/index.tsx
  src/components/organisms/Header/HeaderContainer.tsx
  src/components/organisms/Info/HowReturn/index.tsx
  src/components/pages/Mypage/MypageAccountPage/index.tsx
  src/components/pages/Mypage/MypageContactPage/index.tsx
  src/components/pages/Mypage/MypageInfoPage/index.tsx
  src/components/pages/Mypage/MypageRentPage/index.tsx
  src/components/pages/SignUp/index.tsx
  src/components/pages/admin/store/UI/StoreModal.tsx
  src/components/pages/admin/store/UI/StoreModalBody.tsx
  src/components/pages/home/HomeMainPage.tsx
  src/components/pages/not-found/NotFound.tsx
  src/components/pages/story/UI/StorySection8.tsx
  src/components/templates/admin/AdminMenu.tsx
  src/components/templates/common/BackgroundLayout.tsx
  src/constants/Store.ts
  src/hooks/queries/userQueries.ts
  src/mocks/StoreDetail.tsx
  src/routes/adminRouter.ts
  src/routes/backgroundImageRouter.ts
  src/routes/backgroundRouter.ts
  src/routes/basicRouter.ts
  src/routes/layoutRouter.ts
  src/routes/notLayoutRouter.ts
  src/types/commonTypes.ts
  src/utils/AdminRoutes.tsx
Labels: 💾 Deploy

#230 fix: 콘솔 에러 수정
  index.html
  src/components/atoms/BottomSheet/index.tsx
  src/components/molecules/MobileMenu/index.stories.tsx
  src/components/organisms/NaverMap/index.tsx
  src/components/pages/rent/index.tsx
  src/components/pages/return/index.tsx
Labels: 💾 Deploy

#231 Deploy: Release
  index.html
  src/App.tsx
  src/api/storeApi.ts
  src/components/atoms/BottomSheet/index.tsx
  src/components/atoms/DetailBtn/index.tsx
  src/components/atoms/Header/HeaderMyPage.tsx
  src/components/molecules/ErrorComponent/index.tsx
  src/components/molecules/Footer/FooterLabel/index.tsx
  src/components/molecules/MapBtn/index.tsx
  src/components/molecules/MobileMenu/index.stories.tsx
  src/components/molecules/MobileMenu/index.tsx
  src/components/molecules/Mypage/MypageNav/index.tsx
  src/components/molecules/Store/index.tsx
  src/components/organisms/Header/HeaderContainer.tsx
  src/components/organisms/Info/HowReturn/index.tsx
  src/components/organisms/NaverMap/index.tsx
  src/components/pages/Mypage/MypageAccountPage/index.tsx
  src/components/pages/Mypage/MypageContactPage/index.tsx
  src/components/pages/Mypage/MypageInfoPage/index.tsx
  src/components/pages/Mypage/MypageRentPage/index.tsx
  src/components/pages/SignUp/index.tsx
  src/components/pages/admin/store/UI/StoreModal.tsx
  src/components/pages/admin/store/UI/StoreModalBody.tsx
  src/components/pages/home/HomeMainPage.tsx
  src/components/pages/not-found/NotFound.tsx
  src/components/pages/rent/index.tsx
  src/components/pages/return/index.tsx
  src/components/pages/story/UI/StorySection8.tsx
  src/components/templates/admin/AdminMenu.tsx
  src/components/templates/common/BackgroundLayout.tsx
  src/constants/Store.ts
  src/hooks/queries/userQueries.ts
  src/mocks/StoreDetail.tsx
  src/routes/adminRouter.ts
  src/routes/backgroundImageRouter.ts
  src/routes/backgroundRouter.ts
  src/routes/basicRouter.ts
  src/routes/layoutRouter.ts
  src/routes/notLayoutRouter.ts
  src/types/commonTypes.ts
  src/utils/AdminRoutes.tsx
Labels: 💾 Deploy

#233 Refactor: Signup 요청 리펙토링
  src/components/pages/SignUp/index.tsx
  src/hooks/queries/userQueries.ts
Labels: 💥 Refactor

#232 fix: 회원가입 직후 마이페이지 이동 안되는 에러 수정(로그인 상태 반영)
  src/components/pages/SignUp/index.tsx
Labels: 🛠️ Bug

#237 fix: 로그인 페이지 로그인 텍스트 줄바뀜 문제 수정
  src/components/atoms/Login/LoginTitle/index.tsx
  src/components/molecules/Mypage/MypageRentList/index.tsx
  src/components/pages/Mypage/MypageAccountPage/index.tsx
  src/components/pages/Mypage/MypageInfoPage/index.tsx
  src/components/pages/Mypage/MypageRentPage/index.tsx
  src/components/pages/SignUp/index.tsx
  src/components/templates/SignUp/SignUpNotRequired/index.tsx
  src/components/templates/SignUp/SignUpRequired/index.tsx
  src/types/mypage/MypageTypes.ts
  src/types/signup/SignupTypes.ts
Labels: 🛠️ Bug

#238 deploy: release dev
  src/components/atoms/Login/LoginTitle/index.tsx
  src/components/molecules/Mypage/MypageRentList/index.tsx
  src/components/pages/Mypage/MypageAccountPage/index.tsx
  src/components/pages/Mypage/MypageInfoPage/index.tsx
  src/components/pages/Mypage/MypageRentPage/index.tsx
  src/components/pages/SignUp/index.tsx
  src/components/templates/SignUp/SignUpNotRequired/index.tsx
  src/components/templates/SignUp/SignUpRequired/index.tsx
  src/types/mypage/MypageTypes.ts
  src/types/signup/SignupTypes.ts
Labels: 💾 Deploy
