Repository UPbrella/UPbrella_front, pull requests merged in 2023-08, with the labels that each got.

#28 chore: react-hot-toast 설치
  package-lock.json
  package.json
  src/App.tsx
Labels: 📂 Chore

#27 feat: 협업지점 관리페이지, 조회 API 추가
  src/api/storeApi.ts
  src/components/molecules/SelectBox/index.stories.tsx
  src/components/molecules/SelectBox/index.tsx
  src/components/organisms/admin/StoreTable.tsx
  src/components/pages/admin/store/StoreManagePage.tsx
  src/components/pages/admin/store/UI/StoreFormWrapper.tsx
  src/components/pages/admin/store/UI/StoreList.tsx
  src/components/pages/admin/store/UI/StoreModal.tsx
  src/components/pages/admin/store/UI/StoreModalBody.tsx
  src/components/pages/admin/store/helper.ts
  src/components/templates/admin/AdminWrapper.tsx
  src/constants/Date.ts
  src/constants/Store.ts
  src/hooks/queries/storeQueries.ts
  src/mocks/Stores.tsx
  src/types/admin/StoreTypes.ts
  src/types/commonTypes.ts
  src/utils/admin/storeHelpers.tsx
  src/utils/selectBox.ts
Labels: 📌 Feature

#29 Style/login/02
  src/components/atoms/Login/LoginButton/index.tsx
  src/components/atoms/Login/LoginTitle/index.tsx
  src/components/atoms/SignUp/SignUpFormAllAllowText/index.stories.tsx
  src/components/atoms/SignUp/SignUpFormAllAllowText/index.tsx
  src/components/atoms/SignUp/SignUpFormAllow/index.stories.tsx
  src/components/atoms/SignUp/SignUpFormAllow/index.tsx
  src/components/atoms/SignUp/SignUpFormAllowChevron/index.stories.tsx
  src/components/atoms/SignUp/SignUpFormAllowChevron/index.tsx
  src/components/atoms/SignUp/SignUpFormAllowText/index.stories.tsx
  src/components/atoms/SignUp/SignUpFormAllowText/index.tsx
  src/components/atoms/SignUp/SignUpFormButton/index.stories.tsx
  src/components/atoms/SignUp/SignUpFormButton/index.tsx
  src/components/atoms/SignUp/SignUpFormInput/index.stories.tsx
  src/components/atoms/SignUp/SignUpFormInput/index.tsx
  src/components/atoms/SignUp/SignUpFormInputBankName/index.stories.tsx
  src/components/atoms/SignUp/SignUpFormInputBankName/index.tsx
  src/components/atoms/SignUp/SignUpFormInputTitle/index.stories.tsx
  src/components/atoms/SignUp/SignUpFormInputTitle/index.tsx
  src/components/atoms/SignUp/SignUpFormSubtitle/index.stories.tsx
  src/components/atoms/SignUp/SignUpFormSubtitle/index.tsx
  src/components/atoms/SignUp/SignUpFormTitle/index.stories.tsx
  src/components/atoms/SignUp/SignUpFormTitle/index.tsx
  src/components/organisms/LoginForm/index.stories.tsx
  src/components/organisms/LoginForm/index.tsx
  src/components/templates/Login/index.tsx
Labels: 🎨 Style

#31 feat: 협업지점 주소 입력 컴포넌트 수정 및 추가
  index.html
  src/components/pages/admin/store/UI/Map.tsx
  src/components/pages/admin/store/UI/StoreAddressInput.tsx
Labels: 📌 Feature

#33 feat: 지점 위치 태그(대분류) 개발 (화면, API)
  src/api/storeApi.ts
  src/components/pages/admin/store/StoreManagePage.tsx
  src/components/pages/admin/store/UI/ClassificationTagList.tsx
  src/components/pages/admin/store/UI/ClassificationTagModal.tsx
  src/components/pages/admin/store/helper.ts
  src/hooks/queries/storeQueries.ts
  src/types/admin/StoreTypes.ts
Labels: 🎨 Style, 📌 Feature

#36 Feat/login/04
  .env
  src/components/atoms/Login/LoginButton/index.tsx
  src/components/atoms/SignUp/SignUpFormInputBankName/index.stories.tsx
  src/components/atoms/SignUp/SignUpFormInputBankName/index.tsx
  src/components/atoms/SignUp/SignUpFormInputTitle/index.stories.tsx
  src/components/atoms/SignUp/SignUpFormInputTitle/index.tsx
  src/components/atoms/SignUp/SignUpFormSubtitle/index.tsx
  src/components/organisms/LoginForm/index.tsx
  src/components/pages/Login/LoginPage/index.tsx
  src/components/pages/Login/LoginRedirectPage/index.tsx
  src/components/templates/Login/index.tsx
  src/routes/layoutRouter.ts
Labels: 📌 Feature

#39 feat: 협업지점 이미지 업로드, 삭제 기능 개발
  src/api/storeApi.ts
  src/components/organisms/Modal/index.tsx
  src/components/organisms/admin/StoreTable.tsx
  src/components/pages/admin/store/UI/StoreImagesModal.tsx
  src/components/pages/admin/store/UI/StoreList.tsx
  src/constants/Store.ts
  src/types/admin/StoreTypes.ts
  src/utils/admin/storeHelpers.tsx
Labels: 📌 Feature

#49 release: front production release pipeline
  .env
  .github/workflows/Dockerfile
  .github/workflows/release-ci-cd.yml
  nginx/nginx.conf
  src/components/molecules/FormLocationMolecules/index.stories.tsx
  src/components/pages/return/index.stories.tsx
  src/stories/Button.tsx
  src/stories/Header.tsx
  tsconfig.json
Labels: 📌 Feature

#48 release: front dev release scripts
  .github/workflows/fe-dev-release.yml
  appspec.yml
  scripts/deploy.sh
Labels: 📌 Feature

#51 fix: 라우터 수정
  src/routes/layoutRouter.ts
Labels: 📂 Chore

#43 feat: 협업지점 생성, 수정, 삭제 기능 추가
  src/api/storeApi.ts
  src/components/pages/admin/store/UI/StoreAddressInput.tsx
  src/components/pages/admin/store/UI/StoreFormWrapper.tsx
  src/components/pages/admin/store/UI/StoreModal.tsx
  src/components/pages/admin/store/UI/StoreModalBody.tsx
  src/components/pages/admin/store/helper.ts
  src/constants/Store.ts
  src/types/admin/StoreTypes.ts
  src/utils/admin/storeHelpers.tsx
Labels: 📌 Feature

#55 chore: 배포 모드 설정 및 에러 코드 수정
  .env
  .env.development
  .env.production
  .github/workflows/release-ci-cd.yml
  .github/workflows/release-dev.yml
  .github/workflows/release-production.yml
  package.json
  src/api/storeApi.ts
  src/components/atoms/Form/BankContent/index.stories.tsx
  src/lib/axios.ts
  src/utils/admin/storeHelpers.tsx
Labels: 📂 Chore

#57 Merge: dev to release-dev
  .env
  .env.development
  .env.production
  .github/workflows/release-dev.yml
  .github/workflows/release-production.yml
  .gitignore
  index.html
  package.json
Labels: 📂 Chore

#58 Merge: release-dev to release
  .env
  .env.development
  .env.production
  .github/workflows/release-dev.yml
  .github/workflows/release-production.yml
  .gitignore
  index.html
  package.json
Labels: 📂 Chore

#59 Merge: develop -> release
  index.html
  package-lock.json
  package.json
  src/components/organisms/NaverMap/index.tsx
  vite.config.ts
Labels: 📂 Chore

#61 Merge: release-dev -> release
  .github/workflows/release-dev.yml
Labels: 📂 Chore

#62 Merge: release -> develop
  .github/workflows/release-dev.yml
  .github/workflows/release-production.yml
Labels: 📂 Chore

#64 Merge: release to develop
  .github/workflows/release-dev.yml
  .github/workflows/release-production.yml
Labels: 📂 Chore

#54 feat: SignUp Page UI 완성 + 기능 추가 중
  src/App.tsx
  src/assets/basicbackground.png
  src/components/atoms/SignUp/SignUpFormAllow/index.tsx
  src/components/atoms/SignUp/SignUpFormButton/index.tsx
  src/components/atoms/SignUp/SignUpFormInput/index.tsx
  src/components/atoms/SignUp/SignUpFormInputBankName/index.tsx
  src/components/atoms/SignUp/SignUpFormSubtitle/index.tsx
  src/components/atoms/SignUp/SignUpProgressCircle/index.stories.tsx
  src/components/atoms/SignUp/SignUpProgressCircle/index.tsx
  src/components/molecules/SignUp/SignUpAllAllowBox/index.stories.tsx
  src/components/molecules/SignUp/SignUpAllAllowBox/index.tsx
  src/components/molecules/SignUp/SignUpAllowBox/index.stories.tsx
  src/components/molecules/SignUp/SignUpAllowBox/index.tsx
  src/components/molecules/SignUp/SignUpInputAccountBox/index.stories.tsx
  src/components/molecules/SignUp/SignUpInputAccountBox/index.tsx
  src/components/molecules/SignUp/SignUpInputBox/index.stories.tsx
  src/components/molecules/SignUp/SignUpInputBox/index.tsx
  src/components/molecules/SignUp/SignUpProgress/index.stories.tsx
  src/components/molecules/SignUp/SignUpProgress/index.tsx
  src/components/molecules/SignUp/SignUpText/index.stories.tsx
  src/components/molecules/SignUp/SignUpText/index.tsx
  src/components/pages/SignUp/index.tsx
  src/components/templates/Login/index.tsx
  src/components/templates/SignUp/SignUpNotRequired/index.tsx
  src/components/templates/SignUp/SignUpRequired/index.tsx
  src/components/templates/common/MainLayout.tsx
  src/routes/layoutRouter.ts
  tailwind.config.js
Labels: 🎨 Style, 📌 Feature

#65 refactor: 사용하는 페이지 router 추가 및 수정
  src/App.tsx
  src/components/molecules/Header/HeaderContents.tsx
  src/components/pages/TestSubPage.tsx
  src/components/pages/home/HomeMainPage.tsx
  src/components/pages/not-found/NotFound.tsx
  src/components/pages/rent/index.tsx
  src/components/pages/return/index.tsx
  src/components/templates/SignUp/SignUpRequired/index.tsx
  src/routes/notLayoutRouter.ts
Labels: 🛠️ Bug, 🎨 Style, 📂 Chore, 💥 Refactor

#73 [etc] nginx reverse proxy 설정
  nginx/nginx.conf
Labels: 📌 Feature

#71 Feat: Bank Modal 추가, Bank 선택시 state change 기능
  src/components/atoms/SignUp/SignUpFormInputBankName/index.tsx
  src/components/molecules/SignUp/SignUpInputAccountBox/index.tsx
  src/components/organisms/BankModal/index.tsx
  src/components/pages/SignUp/index.tsx
  src/components/templates/SignUp/SignUpNotRequired/index.tsx
  src/components/templates/SignUp/SignUpRequired/index.tsx
Labels: 🎨 Style, 📌 Feature

#72 feat: 어드민 > 우산 대여, 반납 조회 기능 추가
  package-lock.json
  package.json
  src/App.tsx
  src/api/rentHistoryApi.ts
  src/components/organisms/admin/StoreTable.tsx
  src/components/pages/admin/RentHistoryPage.tsx
  src/components/pages/admin/rent/RentHistoryPage.tsx
  src/components/templates/admin/AdminMenu.tsx
  src/hooks/queries/rentQueries.ts
  src/hooks/queries/storeQueries.ts
  src/routes/adminRouter.ts
  src/types/admin/RentTypes.ts
Labels: 🎨 Style, 📌 Feature
