Repository UPbrella/UPbrella_front, pull requests merged in 2023-12, with the labels that each got.

#260 fix: 이용내역페이지 반납기한, 반납 일자 오류 수정
  src/components/atoms/Mypage/MypageRentSection/index.tsx
Labels: 🛠️ Bug

#261 feat: 어드민 > 보관함 CRUD
  package-lock.json
  package.json
  src/App.tsx
  src/api/lockerApi.ts
  src/components/organisms/Header/HeaderContainer.tsx
  src/components/organisms/Modal/index.tsx
  src/components/pages/admin/locker/LockerAdminPage.tsx
  src/components/pages/admin/locker/LockerModal.tsx
  src/components/pages/admin/store/UI/ClassificationTagList.tsx
  src/components/pages/admin/store/UI/StoreFormWrapper.tsx
  src/components/pages/admin/store/UI/StoreImagesModal.tsx
  src/components/pages/admin/store/UI/StoreModal.tsx
  src/components/pages/admin/store/UI/SubClassificationTagList.tsx
  src/components/pages/admin/umbrella/UI/UmbrellaModal.tsx
  src/components/pages/admin/umbrella/UmbrellaAdminPage.tsx
  src/components/pages/rent/index.tsx
  src/components/pages/return/index.tsx
  src/hooks/queries/feedBackQueries.ts
  src/hooks/queries/formQueries.ts
  src/hooks/queries/lockerQueries.ts
  src/hooks/queries/rentQueries.ts
  src/hooks/queries/storeQueries.ts
  src/hooks/queries/umbrellaQueries.ts
  src/hooks/queries/userQueries.ts
  src/routes/adminRouter.ts
  src/types/admin/lockersTypes.ts
Labels: 📌 Feature

#263 Deploy: release Dev
  package-lock.json
  package.json
  src/App.tsx
  src/api/lockerApi.ts
  src/components/atoms/Mypage/MypageRentSection/index.tsx
  src/components/organisms/Header/HeaderContainer.tsx
  src/components/organisms/Modal/index.tsx
  src/components/pages/admin/locker/LockerAdminPage.tsx
  src/components/pages/admin/locker/LockerModal.tsx
  src/components/pages/admin/store/UI/ClassificationTagList.tsx
  src/components/pages/admin/store/UI/StoreFormWrapper.tsx
  src/components/pages/admin/store/UI/StoreImagesModal.tsx
  src/components/pages/admin/store/UI/StoreModal.tsx
  src/components/pages/admin/store/UI/SubClassificationTagList.tsx
  src/components/pages/admin/umbrella/UI/UmbrellaModal.tsx
  src/components/pages/admin/umbrella/UmbrellaAdminPage.tsx
  src/components/pages/rent/index.tsx
  src/components/pages/return/index.tsx
  src/hooks/queries/feedBackQueries.ts
  src/hooks/queries/formQueries.ts
  src/hooks/queries/lockerQueries.ts
  src/hooks/queries/rentQueries.ts
  src/hooks/queries/storeQueries.ts
  src/hooks/queries/umbrellaQueries.ts
  src/hooks/queries/userQueries.ts
  src/routes/adminRouter.ts
  src/types/admin/lockersTypes.ts
Labels: 💾 Deploy

#264 Deploy: release
  package-lock.json
  package.json
  src/App.tsx
  src/api/lockerApi.ts
  src/components/atoms/Mypage/MypageRentSection/index.tsx
  src/components/organisms/Header/HeaderContainer.tsx
  src/components/organisms/Modal/index.tsx
  src/components/pages/admin/locker/LockerAdminPage.tsx
  src/components/pages/admin/locker/LockerModal.tsx
  src/components/pages/admin/store/UI/ClassificationTagList.tsx
  src/components/pages/admin/store/UI/StoreFormWrapper.tsx
  src/components/pages/admin/store/UI/StoreImagesModal.tsx
  src/components/pages/admin/store/UI/StoreModal.tsx
  src/components/pages/admin/store/UI/SubClassificationTagList.tsx
  src/components/pages/admin/umbrella/UI/UmbrellaModal.tsx
  src/components/pages/admin/umbrella/UmbrellaAdminPage.tsx
  src/components/pages/rent/index.tsx
  src/components/pages/return/index.tsx
  src/hooks/queries/feedBackQueries.ts
  src/hooks/queries/formQueries.ts
  src/hooks/queries/lockerQueries.ts
  src/hooks/queries/rentQueries.ts
  src/hooks/queries/storeQueries.ts
  src/hooks/queries/umbrellaQueries.ts
  src/hooks/queries/userQueries.ts
  src/routes/adminRouter.ts
  src/types/admin/lockersTypes.ts
Labels: 💾 Deploy

#265 Chore: 배포 방법 변경
  .github/workflows/release-production.yml
Labels: 📂 Chore

#268 feat: 지점 렌더링 버그 등 기타 수정
  src/components/pages/RentalLocation/RentalLocationPage.tsx
  src/components/pages/SignUp/index.tsx
  src/components/pages/admin/store/UI/StoreModalBody.tsx
  src/hooks/queries/userQueries.ts
  src/routes/basicRouter.ts
  src/routes/notLayoutRouter.ts
  src/utils/AdminRoutes.tsx
  src/utils/PrivateRoutes.tsx
Labels: 🛠️ Bug, 💥 Refactor

#272 Deploy: Dev
  src/components/atoms/Form/RentModalAccount/index.tsx
Labels: 💾 Deploy

#273 Deploy: Release
  src/components/atoms/Form/RentModalAccount/index.tsx
Labels: 💾 Deploy

#274 chore: 구글 서치 콘솔 메타 태그, sitemap 추가
  index.html
  public/sitemap.xml
Labels: 📂 Chore

#275 Deploy: Dev
  index.html
  public/sitemap.xml
Labels: 💾 Deploy

#276 Deploy: Release
  index.html
  public/sitemap.xml
Labels: 💾 Deploy

#277 chore: naver search advisor 메타 태그 추가
  index.html
  public/robots.txt
Labels: 📂 Chore

#278 Deplpy: Dev
  index.html
  public/robots.txt
Labels: 💾 Deploy

#279 Deploy: Release
  index.html
  public/robots.txt
Labels: 💾 Deploy

#280 fix: 대여 오류 문구 수정
  src/components/pages/rent/index.tsx
Labels: ✍️ Code Style

#281 fix: 대여, 반납 폼 빈 화면 버그 수정
  src/utils/PrivateRoutes.tsx
Labels: 🛠️ Bug

#283 Deploy: Release
  src/components/pages/rent/index.tsx
  src/utils/PrivateRoutes.tsx
Labels: 💾 Deploy

#286 feat: 프리텐다드 폰트 추가
  src/main.tsx
  src/styles/fonts/font.css
  src/styles/fonts/subset-PretendardJP-Bold.woff
  src/styles/fonts/subset-PretendardJP-Bold.woff2
  src/styles/fonts/subset-PretendardJP-Regular.woff
  src/styles/fonts/subset-PretendardJP-Regular.woff2
  src/styles/fonts/subset-PretendardJP-SemiBold.woff
  src/styles/fonts/subset-PretendardJP-SemiBold.woff2
Labels: 🎨 Style

#287 Deploy: Dev
  src/components/pages/admin/locker/LockerAdminPage.tsx
  src/components/pages/admin/locker/LockerModal.tsx
  src/main.tsx
  src/styles/fonts/font.css
  src/styles/fonts/subset-PretendardJP-Bold.woff
  src/styles/fonts/subset-PretendardJP-Bold.woff2
  src/styles/fonts/subset-PretendardJP-Regular.woff
  src/styles/fonts/subset-PretendardJP-Regular.woff2
  src/styles/fonts/subset-PretendardJP-SemiBold.woff
  src/styles/fonts/subset-PretendardJP-SemiBold.woff2
Labels: 💾 Deploy

#288 Deploy: Release
  src/components/pages/admin/locker/LockerAdminPage.tsx
  src/components/pages/admin/locker/LockerModal.tsx
  src/main.tsx
  src/styles/fonts/font.css
  src/styles/fonts/subset-PretendardJP-Bold.woff
  src/styles/fonts/subset-PretendardJP-Bold.woff2
  src/styles/fonts/subset-PretendardJP-Regular.woff
  src/styles/fonts/subset-PretendardJP-Regular.woff2
  src/styles/fonts/subset-PretendardJP-SemiBold.woff
  src/styles/fonts/subset-PretendardJP-SemiBold.woff2
Labels: 💾 Deploy

#290 chore: seo > react helmet, react-snap
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/components/pages/Info/InfoPage.tsx
  src/components/pages/Login/LoginPage/index.tsx
  src/components/pages/RentalLocation/RentalLocationPage.tsx
  src/components/pages/SignUp/index.tsx
  src/components/pages/contact/ContactPage.tsx
  src/components/pages/officeDetail/OfficeDetailPage.tsx
  src/components/pages/pp/index.tsx
  src/components/pages/rentalOffice/RentalOfficePage.tsx
  src/components/pages/tos/index.tsx
  src/main.tsx
  src/utils/AdminRoutes.tsx
  src/utils/SeoMetaTag.tsx
Labels: 📂 Chore

#291 Deploy: Dev
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/api/formApi.ts
  src/components/pages/Info/InfoPage.tsx
  src/components/pages/Login/LoginPage/index.tsx
  src/components/pages/RentalLocation/RentalLocationPage.tsx
  src/components/pages/SignUp/index.tsx
  src/components/pages/contact/ContactPage.tsx
  src/components/pages/officeDetail/OfficeDetailPage.tsx
  src/components/pages/pp/index.tsx
  src/components/pages/rent/index.tsx
  src/components/pages/rentalOffice/RentalOfficePage.tsx
  src/components/pages/return/index.tsx
  src/components/pages/tos/index.tsx
  src/hooks/queries/formQueries.ts
  src/main.tsx
  src/types/form/FormTypes.ts
  src/utils/AdminRoutes.tsx
  src/utils/SeoMetaTag.tsx
Labels: 💾 Deploy

#292 fix: react-snap 삭제
  package-lock.json
  package.json
  src/main.tsx
Labels: 💾 Deploy

#293 Deploy: Dev
  package-lock.json
  package.json
  src/main.tsx
Labels: 💾 Deploy

#294 fix: 대여 폼 버그 수정
  src/api/formApi.ts
  src/components/atoms/Form/RentModalAccount/index.tsx
  src/components/atoms/Form/RentModalStorageIssue/index.tsx
  src/components/pages/rent/index.tsx
Labels: 🛠️ Bug

#295 fix: 어드민 > 우산 관리 버그 수정 및 리팩토링
  src/components/pages/admin/umbrella/UI/UmbrellaExcelButton.tsx
  src/components/pages/admin/umbrella/UI/UmbrellaModal.tsx
  src/components/pages/admin/umbrella/UmbrellaAdminPage.tsx
  src/components/pages/admin/umbrella/helper.ts
  src/hooks/queries/umbrellaQueries.ts
Labels: 🛠️ Bug, 💥 Refactor

#296 Deploy: Dev
  src/api/formApi.ts
  src/components/atoms/Form/RentModalAccount/index.tsx
  src/components/atoms/Form/RentModalStorageIssue/index.tsx
  src/components/pages/admin/umbrella/UI/UmbrellaExcelButton.tsx
  src/components/pages/admin/umbrella/UI/UmbrellaModal.tsx
  src/components/pages/admin/umbrella/UmbrellaAdminPage.tsx
  src/components/pages/admin/umbrella/helper.ts
  src/components/pages/rent/index.tsx
  src/hooks/queries/umbrellaQueries.ts
Labels: 💾 Deploy

#297 chore: meta robots 태그 추가 (dev, noindex)
  src/utils/SeoMetaTag.tsx
Labels: 📂 Chore

#298 Deploy: Dev
  src/utils/SeoMetaTag.tsx
Labels: 💾 Deploy

#299 Deploy: Release
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/api/formApi.ts
  src/components/atoms/Form/RentModalAccount/index.tsx
  src/components/atoms/Form/RentModalStorageIssue/index.tsx
  src/components/pages/Info/InfoPage.tsx
  src/components/pages/Login/LoginPage/index.tsx
  src/components/pages/RentalLocation/RentalLocationPage.tsx
  src/components/pages/SignUp/index.tsx
  src/components/pages/admin/umbrella/UI/UmbrellaExcelButton.tsx
  src/components/pages/admin/umbrella/UI/UmbrellaModal.tsx
  src/components/pages/admin/umbrella/UmbrellaAdminPage.tsx
  src/components/pages/admin/umbrella/helper.ts
  src/components/pages/contact/ContactPage.tsx
  src/components/pages/officeDetail/OfficeDetailPage.tsx
  src/components/pages/pp/index.tsx
  src/components/pages/rent/index.tsx
  src/components/pages/rentalOffice/RentalOfficePage.tsx
  src/components/pages/return/index.tsx
  src/components/pages/tos/index.tsx
  src/hooks/queries/formQueries.ts
  src/hooks/queries/umbrellaQueries.ts
  src/main.tsx
  src/types/form/FormTypes.ts
  src/utils/AdminRoutes.tsx
  src/utils/SeoMetaTag.tsx
Labels: 💾 Deploy

#300 fix: 협업지점 api - 비밀번호 필드 삭제 반영
  index.html
  src/components/pages/admin/store/UI/StoreModalBody.tsx
  src/components/pages/admin/store/helper.ts
  src/types/admin/StoreTypes.ts
  src/utils/SeoMetaTag.tsx
Labels: ✍️ Code Style

#301 Deploy: Dev
  index.html
  src/components/pages/admin/store/UI/StoreModalBody.tsx
  src/components/pages/admin/store/helper.ts
  src/types/admin/StoreTypes.ts
  src/utils/SeoMetaTag.tsx
Labels: 💾 Deploy

#302 Deploy: Release
  index.html
  src/components/pages/admin/store/UI/StoreModalBody.tsx
  src/components/pages/admin/store/helper.ts
  src/types/admin/StoreTypes.ts
  src/utils/SeoMetaTag.tsx
Labels: 💾 Deploy

#303 chore: 구글 서치 콘솔 dev meta 태그 추가
  index.html
Labels: 📂 Chore

#304 chore: 구글 서치 콘솔 dev meta 태그 추가
  index.html
Labels: 💾 Deploy

#306 Deploy: Dev
  src/api/formApi.ts
  src/components/atoms/Form/RentModalStorageIssue/index.tsx
  src/components/pages/admin/locker/LockerAdminPage.tsx
  src/components/pages/admin/locker/LockerModal.tsx
  src/components/pages/rent/index.tsx
  src/hooks/queries/formQueries.ts
  src/types/form/FormTypes.ts
Labels: 💾 Deploy

#307 fix: toast 메세지 수정
  src/components/pages/admin/rent/RentHistoryPage.tsx
  src/components/pages/rent/index.tsx
  src/components/pages/return/index.tsx
  src/main.tsx
Labels: 💥 Refactor

#308 Deploy: Dev
  src/components/pages/admin/rent/RentHistoryPage.tsx
  src/components/pages/rent/index.tsx
  src/components/pages/return/index.tsx
  src/main.tsx
Labels: 💾 Deploy

#309 Deploy: Release
  index.html
  src/api/formApi.ts
  src/components/atoms/Form/RentModalStorageIssue/index.tsx
  src/components/pages/admin/locker/LockerAdminPage.tsx
  src/components/pages/admin/locker/LockerModal.tsx
  src/components/pages/admin/rent/RentHistoryPage.tsx
  src/components/pages/rent/index.tsx
  src/components/pages/return/index.tsx
  src/hooks/queries/formQueries.ts
  src/main.tsx
  src/types/form/FormTypes.ts
Labels: 💾 Deploy
