Repository UPbrella/UPbrella_front, pull requests merged in 2025-06, with the labels that each got.

#321 Release Prod
  package-lock.json
  package.json
  src/components/organisms/Header/HeaderContainer.tsx
  src/components/pages/admin/rent/RentHistoryPage.tsx
  src/components/pages/admin/rent/helper.ts
  src/components/pages/admin/user/UserAdminPage.tsx
  src/components/pages/admin/user/helper.ts
  src/hooks/queries/userQueries.ts
  src/types/admin/userTypes.ts
  vercel.json
  vite.config.ts
Labels: 💾 Deploy

#322 feat: 2024, 2025 상반기 활동 추가
  src/components/pages/story/UI/StorySection7.tsx
  src/components/pages/story/data.ts
Labels: 📌 Feature

#325 fix: 랜딩 페이지 > 좌우 스크롤 제거
  src/components/organisms/Footer/index.tsx
Labels: 🛠️ Bug

#326 Release
  src/components/organisms/Footer/index.tsx
Labels: 💾 Deploy

#327 fix: footer 너비 100% 설정
  src/components/organisms/Footer/index.tsx
Labels: 🛠️ Bug

#328 Release
  src/components/organisms/Footer/index.tsx
Labels: 💾 Deploy
